CREATE TABLE OKAY_CAR_REGISTER(
   CAR_NUM VARCHAR2(10) PRIMARY KEY, -- 차량번호 중복불가
   MANUFACTOR VARCHAR2(50) NOT NULL,
   MODEL VARCHAR2(50) NOT NULL,
   VOLUME VARCHAR2(50) NOT NULL,
   PRICE NUMBER NOT NULL,
   ACCIDENT_CNT NUMBER NOT NULL,
   DRIVE_DIST NUMBER(6) NOT NULL,
   REGIST_TIME DATE NOT NULL, -- 등록시간을 기준으로 정렬가능
   SELL_OR_NOT VARCHAR2(1) NOT NULL,
   -- 차량 이미지 외래키 설정
   FOREIGN KEY (MODEL) REFERENCES CAR_IMG (MODEL)
);

CREATE TABLE CAR_IMG(
   MODEL VARCHAR2(50) PRIMARY KEY,
   IMG_SRC VARCHAR2(100)
);

INSERT INTO CAR_IMG VALUES ('K5','../car_img/kia_k5.png');

INSERT INTO OKAY_CAR_REGISTER VALUES 
('12가1234','기아','K5','2.0 가솔린',6500000,1,15000,SYSDATE,'N');

SELECT * FROM OKAY_CAR_REGISTER o, CAR_IMG ci
WHERE SELL_OR_NOT='N'
AND o.model = ci.model
order by REGIST_TIME;

SELECT *
FROM OKAY_CAR_REGISTER o, CAR_IMG ci
WHERE car_num = '12가1234'
AND o.MODEL = ci.MODEL;