-- 판매등록차량정보
CREATE TABLE OKAY_CAR_REGISTER(
	CAR_NUM VARCHAR2(10) PRIMARY KEY, -- 차량번호 중복불가
	MANUFACTOR VARCHAR2(50) NOT NULL,
	MODEL VARCHAR2(50) NOT NULL,
	VOLUME VARCHAR2(50) NOT NULL,
	PRICE NUMBER NOT NULL,
	ACCIDENT_CNT NUMBER NOT NULL,
	DRIVE_DIST NUMBER(6) NOT NULL,
	REGIST_TIME DATE NOT NULL, -- 등록시간을 기준으로 정렬가능
	SELL_OR_NOT VARCHAR2(1) NOT NULL,
	-- 차량 이미지 외래키 설정
	FOREIGN KEY (MODEL) REFERENCES CAR_IMG (MODEL)
);

-- 차량이미지
CREATE TABLE CAR_IMG(
	MODEL VARCHAR2(50) PRIMARY KEY,
	IMG_SRC VARCHAR2(100)
);

-- 테이블 삭제
DROP TABLE CAR_IMG;
DROP TABLE OKAY_CAR_REGISTER ;

-- 테이블 조회
SELECT * FROM CAR_IMG ci ;
SELECT * FROM OKAY_CAR_REGISTER ocr ;

-- 임시데이터 삽입 
INSERT INTO CAR_IMG VALUES ('쏘나타','');
INSERT INTO CAR_IMG VALUES ('K5','');
INSERT INTO CAR_IMG VALUES ('K8','');
INSERT INTO OKAY_CAR_REGISTER VALUES 
('12가1234','기아','K5','2.0 가솔린',1500,1,15000,SYSDATE,'N');
INSERT INTO OKAY_CAR_REGISTER VALUES 
('33바5424','기아','K8','3.3 가솔린',3200,0,15000,SYSDATE,'N');
INSERT INTO OKAY_CAR_REGISTER VALUES 
('17고4433','기아','K5','2.0 가솔린',2000,1,15000,SYSDATE,'N');

-- join sql문
SELECT ci.img_src,ok.* FROM car_img ci, OKAY_CAR_REGISTER ok WHERE ci.model=ok.model

/*
INSERT INTO OKAY_CAR_REGISTER VALUES 
(?,?,?,?,?,?,?,SYSDATE,'N')
 */

